service: log-management
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  memorySize: 128 # Default 1024 MB
  timeout: 60 # Default 6 seconds
  environment:
    S3_LOG_BUCKET: ${self:custom.secrets.S3_LOG_BUCKET}
    RETENTION_DAYS: ${self:custom.secrets.RETENTION_DAYS}
    CLOUDWATCH_LOGS: ${self:custom.secrets.CLOUDWATCH_LOGS}
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - "arn:aws:iam::aws:policy/AWSLambdaExecute"
    - "arn:aws:iam::aws:policy/CloudWatchEventsFullAccess"
    - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        # Check if bucket exists and if have permission to access
        - "s3:HeadBucket"
      Resource:
        - "*"
functions:
  logRotation:
    handler: handler.log_rotation
    name: ${self:service}-logRotation
  collect:
    handler: handler.collect
    name: ${self:service}-collect
